

CXXFLAGS += \
	-std=c++14 \
	-Wconversion \
	-Wall -Wextra \
	-pedantic-errors \
	-Wstrict-aliasing \
	-Wno-unused-parameter

PROGRAMS := add-github-syntax-highlights

all: $(PROGRAMS)

clean:
	$(RM) $(PROGRAMS)